default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: alpha_color_development

test:
  <<: *default
  database: alpha_color_test

production:
  <<: *default
  database: alpha_color_production
